### ISSUE TITLE
The filter by inequality example fails

### ISSUE THREAD

**Issue by retrography** [dkuppitz/sql2gremlin#4]
Running the sample query for inequality on gremlin-groovy-2.6.0 I encountered the following error:

```gremlin
gremlin> g.V('type','product').hasNot('unitPrice', T.gt, 10f).map()
No signature of method: com.tinkerpop.gremlin.groovy.GremlinGroovyPipeline.hasNot() is applicable for argument types: (java.lang.String, com.tinkerpop.gremlin.Tokens$T, java.lang.Float) values: [unitPrice, gt, 10.0]
Possible solutions: hasNot(java.lang.String), hasNot(java.lang.String, java.lang.Object), hasNext(), last(), has(java.lang.String, com.tinkerpop.gremlin.Tokens$T, java.lang.Object), hashCode()
Display stack trace? [yN]
groovy.lang.MissingMethodException: No signature of method: com.tinkerpop.gremlin.groovy.GremlinGroovyPipeline.hasNot() is applicable for argument types: (java.lang.String, com.tinkerpop.gremlin.Tokens$T, java.lang.Float) values: [unitPrice, gt, 10.0]
Possible solutions: hasNot(java.lang.String), hasNot(java.lang.String, java.lang.Object), hasNext(), last(), has(java.lang.String, com.tinkerpop.gremlin.Tokens$T, java.lang.Object), hashCode()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at groovysh_evaluate.run(groovysh_evaluate:51)
	at groovysh_evaluate$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at groovysh_evaluate$run.call(Unknown Source)
	at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
	at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
	at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
	at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
	at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
	at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
	at com.tinkerpop.gremlin.groovy.console.Console.<init>(Console.java:60)
	at com.tinkerpop.gremlin.groovy.console.Console.main(Console.java:102)
```

**Comment by dkuppitz** [comment]
Thanks for pointing that out. It took a while until somebody found it :). It's fixed now.

**Comment by retrography** [comment]
But now there is no example for 'gt' and 'lt' comparisons anymore... :)

**Comment by dkuppitz** [comment]
Now it's in**equality**, everything else is not supported by `.hasNot()`.

**Comment by retrography** [comment]
That I understands. What I meant is that you may want to add an inequality to another snippet, for instance the .has() example, so that the tutorial covers the inequalities as well.


—
